# Generated by Django 5.0.6 on 2024-05-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_users',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('Name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
